const { contextBridge, ipcRenderer, webUtils } = require('electron')

const on = (channel) => (callback) => {
  if (typeof callback !== 'function') return () => {}
  const listener = (_event, payload) => callback(payload)
  ipcRenderer.on(channel, listener)
  return () => ipcRenderer.removeListener(channel, listener)
}

const call = (method, args) => ipcRenderer.invoke('launcher:server-local', { method, args: args || [] })
const localEvent = (type, map) => (callback) => {
  if (typeof callback !== 'function') return () => {}
  const listener = (_event, payload) => {
    if (!payload || payload.type !== type) return
    callback(map ? map(payload) : payload)
  }
  ipcRenderer.on('luns:launcher-event', listener)
  return () => ipcRenderer.removeListener('luns:launcher-event', listener)
}

contextBridge.exposeInMainWorld('electronAPI', {
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (patch) => ipcRenderer.invoke('settings:set', patch),
  setSecret: (name, value) => ipcRenderer.invoke('secret:set', { name, value }),
  getSecret: (name) => ipcRenderer.invoke('secret:get', { name }).then((r) => r?.value || ''),
  getAppInfo: () => ipcRenderer.invoke('app:info'),
  discordState: () => ipcRenderer.invoke('discord:state'),
  discordSelect: (instance) => ipcRenderer.invoke('discord:select', instance),
  getVersion: async () => (await ipcRenderer.invoke('app:info'))?.version || '',
  getPlatform: async () => (await ipcRenderer.invoke('app:info'))?.platform || '',

  listVersions: (opts) => ipcRenderer.invoke('launcher:versions', opts),
  listLoaderVersions: (opts) => ipcRenderer.invoke('launcher:loaders', opts),
  listLoaderGames: (opts) => ipcRenderer.invoke('launcher:loader-games', opts),
  listInstances: () => ipcRenderer.invoke('launcher:instances'),
  listAccounts: () => ipcRenderer.invoke('launcher:accounts'),
  addAccount: (opts) => ipcRenderer.invoke('launcher:account-add', opts),
  signInAccount: (opts) => ipcRenderer.invoke('launcher:account-signin', opts),
  refreshAccount: (opts) => ipcRenderer.invoke('launcher:account-refresh', opts),
  resolveSkin: (opts) => ipcRenderer.invoke('skin:resolve', opts),
  removeAccount: (opts) => ipcRenderer.invoke('launcher:account-remove', opts),
  setActiveAccount: (opts) => ipcRenderer.invoke('launcher:account-active', opts),
  systemInfo: () => ipcRenderer.invoke('launcher:system'),
  storage: () => ipcRenderer.invoke('launcher:storage'),
  createInstance: (opts) => ipcRenderer.invoke('launcher:create', opts),
  updateInstance: (opts) => ipcRenderer.invoke('launcher:update', opts),
  removeInstance: (opts) => ipcRenderer.invoke('launcher:remove', opts),
  launchInstance: (opts) => ipcRenderer.invoke('launcher:launch', opts),
  stopInstance: (opts) => ipcRenderer.invoke('launcher:stop', opts),
  instanceLogs: (opts) => ipcRenderer.invoke('launcher:logs', opts),
  runningInstances: () => ipcRenderer.invoke('launcher:running'),
  listDir: (opts) => ipcRenderer.invoke('launcher:dir', opts),
  toggleFile: (opts) => ipcRenderer.invoke('launcher:toggle-file', opts),
  deleteFile: (opts) => ipcRenderer.invoke('launcher:delete-file', opts),
  deleteFiles: (opts) => ipcRenderer.invoke('launcher:delete-files', opts),
  trashFiles: (opts) => ipcRenderer.invoke('launcher:trash-files', opts),
  listTrash: (opts) => ipcRenderer.invoke('launcher:trash-list', opts),
  restoreTrash: (opts) => ipcRenderer.invoke('launcher:trash-restore', opts),
  purgeTrash: (opts) => ipcRenderer.invoke('launcher:trash-purge', opts),
  createEntry: (opts) => ipcRenderer.invoke('launcher:create-entry', opts),
  importPaths: (opts) => ipcRenderer.invoke('launcher:import-paths', opts),
  moveEntry: (opts) => ipcRenderer.invoke('launcher:move-entry', opts),
  pathForFile: (file) => {
    try {
      return webUtils.getPathForFile(file)
    } catch {
      return ''
    }
  },
  readFile: (opts) => ipcRenderer.invoke('launcher:read-file', opts),
  writeFile: (opts) => ipcRenderer.invoke('launcher:write-file', opts),
  listJavaRuntimes: (opts) => ipcRenderer.invoke('launcher:runtimes', opts),
  installJavaRuntime: (opts) => ipcRenderer.invoke('launcher:runtime-install', opts),
  removeJavaRuntime: (opts) => ipcRenderer.invoke('launcher:runtime-remove', opts),

  modpackSearch: (opts) => ipcRenderer.invoke('launcher:modpack-search', opts),
  modpackTags: (opts) => ipcRenderer.invoke('launcher:modpack-tags', opts),
  modpackVersions: (opts) => ipcRenderer.invoke('launcher:modpack-versions', opts),
  modpackResolve: (opts) => ipcRenderer.invoke('launcher:modpack-resolve', opts),
  modpackImport: (opts) => ipcRenderer.invoke('launcher:modpack-import', opts),
  modpackInstall: (opts) => ipcRenderer.invoke('launcher:modpack-install', opts),
  modpackRepair: (opts) => ipcRenderer.invoke('launcher:modpack-repair', opts),
  chooseModpack: () => ipcRenderer.invoke('launcher:choose-modpack'),
  exportProfile: (opts) => ipcRenderer.invoke('launcher:export-profile', opts),
  serverpackPlan: (opts) => ipcRenderer.invoke('launcher:serverpack-plan', opts),
  instanceTree: (opts) => ipcRenderer.invoke('launcher:instance-tree', opts),
  serverpackWalk: (opts) => ipcRenderer.invoke('launcher:serverpack-walk', opts),
  serverpackExport: (opts) => ipcRenderer.invoke('launcher:serverpack-export', opts),
  serverTestEggs: () => ipcRenderer.invoke('launcher:server-test-eggs'),
  serverTestList: () => ipcRenderer.invoke('launcher:server-test-list'),
  serverTestSuggest: (opts) => ipcRenderer.invoke('launcher:server-test-suggest', opts),
  serverTestDefaults: (opts) => ipcRenderer.invoke('launcher:server-test-defaults', opts),
  serverTestCreate: (opts) => ipcRenderer.invoke('launcher:server-test-create', opts),
  serverTestCopy: (opts) => ipcRenderer.invoke('launcher:server-test-copy', opts),
  serverTestUpdate: (opts) => ipcRenderer.invoke('launcher:server-test-update', opts),
  serverTestRemove: (opts) => ipcRenderer.invoke('launcher:server-test-remove', opts),
  serverTestInstall: (opts) => ipcRenderer.invoke('launcher:server-test-install', opts),
  serverTestStart: (opts) => ipcRenderer.invoke('launcher:server-test-start', opts),
  serverTestStop: (opts) => ipcRenderer.invoke('launcher:server-test-stop', opts),
  serverTestCommand: (opts) => ipcRenderer.invoke('launcher:server-test-command', opts),
  serverTestStatus: (opts) => ipcRenderer.invoke('launcher:server-test-status', opts),
  serverTestLogs: (opts) => ipcRenderer.invoke('launcher:server-test-logs', opts),
  serverTestClearLogs: (opts) => ipcRenderer.invoke('launcher:server-test-clear-logs', opts),
  updateStatus: () => ipcRenderer.invoke('update:status'),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateDownload: () => ipcRenderer.invoke('update:download'),
  updateInstall: () => ipcRenderer.invoke('update:install'),
  contentSearch: (opts) => ipcRenderer.invoke('launcher:content-search', opts),
  instanceModEnvs: (opts) => ipcRenderer.invoke('launcher:instance-mod-env', opts),
  hostStatus: (opts) => ipcRenderer.invoke('launcher:host-status', opts),
  hostInstallAgent: () => ipcRenderer.invoke('launcher:host-install-agent'),
  hostSetToken: (opts) => ipcRenderer.invoke('launcher:host-set-token', opts),
  hostStart: (opts) => ipcRenderer.invoke('launcher:host-start', opts),
  hostStop: () => ipcRenderer.invoke('launcher:host-stop'),
  contentVersions: (opts) => ipcRenderer.invoke('launcher:content-versions', opts),
  contentProject: (opts) => ipcRenderer.invoke('launcher:content-project', opts),
  contentTags: (opts) => ipcRenderer.invoke('launcher:content-tags', opts),
  folderIcons: (opts) => ipcRenderer.invoke('launcher:folder-icons', opts),
  worldTree: (opts) => ipcRenderer.invoke('launcher:world-tree', opts),
  worldRead: (opts) => ipcRenderer.invoke('launcher:world-read', opts),
  worldWrite: (opts) => ipcRenderer.invoke('launcher:world-write', opts),
  worldRestore: (opts) => ipcRenderer.invoke('launcher:world-restore', opts),
  contentChangelog: (opts) => ipcRenderer.invoke('launcher:content-changelog', opts),
  contentInstalled: (opts) => ipcRenderer.invoke('launcher:content-installed', opts),
  contentInstall: (opts) => ipcRenderer.invoke('launcher:content-install', opts),

  getCrash: (opts) => ipcRenderer.invoke('launcher:crash', opts),
  uploadLog: (opts) => ipcRenderer.invoke('launcher:upload-log', opts),
  saveLog: (opts) => ipcRenderer.invoke('launcher:save-log', opts),

  chooseDirectory: (opts) => ipcRenderer.invoke('launcher:choose-dir', opts),
  chooseJava: () => ipcRenderer.invoke('launcher:choose-java'),
  revealPath: (target) => ipcRenderer.invoke('launcher:reveal', { target }),
  onLauncherEvent: on('luns:launcher-event'),

  clipboardWrite: (text) => ipcRenderer.invoke('clipboard:write', text),
  openExternal: (url) => ipcRenderer.invoke('shell:open', url),

  getServerConfigs: () => call('configs'),
  getServerConfig: (id) => call('config', [id]),
  getServerStatus: (id) => call('status', [id]),
  getServerHistory: (id) => call('history', [id]),
  getServerTps: (id) => call('tps', [id]),
  wingsServerState: (id) => call('state', [id]),
  wingsServerPower: (id, action) => call('power', [id, action]),
  startGameServer: (id) => call('power', [id, 'start']),
  stopGameServer: (id) => call('power', [id, 'stop']),
  killGameServer: (id) => call('power', [id, 'kill']),
  wingsServerLogs: (id, lines) => call('logs', [id, lines]),
  serverGetLogs: (id) => call('logEntries', [id]),
  wingsServerCommand: (id, command) => call('command', [id, command]),
  wingsListFiles: (id, dir) => call('fileList', [id, dir]),
  wingsReadFile: (id, file) => call('fileRead', [id, file]),
  wingsWriteFile: (id, file, content) => call('fileWrite', [id, file, content]),
  wingsDeleteFile: (id, file) => call('fileDelete', [id, file]),
  wingsCreateFile: (id, dir, name) => call('fileCreate', [id, dir, name, false]),
  wingsCreateFolder: (id, dir, name) => call('fileCreate', [id, dir, name, true]),
  wingsMoveFile: (id, from, to) => call('fileMove', [id, from, to]),
  wingsUploadFile: (id, dest, data) => call('fileUpload', [id, dest, data]),
  wingsSyncConfig: (id, patch) => call('syncConfig', [id, patch]),
  installServer: (id) => call('install', [id]),
  wingsDeleteServer: (id) => call('remove', [id]),
  serverLocalPruneMods: (id) => call('pruneClientMods', [id]),
  serverLocalTrash: () => call('trashList'),
  serverLocalRestore: (trashId) => call('trashRestore', [trashId]),
  serverLocalPurge: (trashId) => call('trashPurge', [trashId]),
  removeServerConfig: () => Promise.resolve({ ok: true }),
  databaseSetup: (name, user, pass) => call('databaseSetup', [name, user, pass]),
  wingsWsConnect: (id) => call('wsConnect', [id]),
  wingsWsDisconnect: (id) => call('wsDisconnect', [id]),
  wingsWsStatus: (id) => call('wsStatus', [id]),
  wingsWsSend: (id, event, args) => call('wsSend', [id, event, args]),
  backupList: (id) => call('backupList', [id]),
  backupCreate: (id, payload) => call('backupCreate', [id, payload]),
  backupUpdate: (id, uuid, patch) => call('backupUpdate', [id, uuid, patch]),
  backupRestore: (id, uuid, opts) => call('backupRestore', [id, uuid, opts]),
  backupDelete: (id, uuid) => call('backupDelete', [id, uuid]),
  backupDownload: (id, uuid) => call('backupDownload', [id, uuid]),
  scheduleList: (id) => call('scheduleList', [id]),
  schedulePreview: (expr) => call('schedulePreview', [expr]),
  scheduleCreate: (id, payload) => call('scheduleCreate', [id, payload]),
  scheduleUpdate: (id, payload) => call('scheduleUpdate', [id, payload]),
  scheduleToggle: (id, active) => call('scheduleToggle', [id, active]),
  scheduleRun: (id) => call('scheduleRun', [id]),
  scheduleDelete: (id) => call('scheduleDelete', [id]),

  onServerLog: localEvent('server-log', (ev) => ({ serverId: ev.serverId, message: ev.message })),
  onServerLogSnapshot: localEvent('server-log-snapshot', (ev) => ({ serverId: ev.serverId, logs: ev.logs })),
  onServerLogReset: localEvent('server-log-reset', (ev) => ({ serverId: ev.serverId })),
  onServerProgress: localEvent('server-progress', (ev) => ({ serverId: ev.serverId, percent: ev.percent, message: ev.message })),
  onServerTps: localEvent('server-tps', (ev) => ({ serverId: ev.serverId, tps: ev.tps })),
  onWingsWsEvent: localEvent('wings-ws', (ev) => ({ serverId: ev.serverId, event: ev.event, payload: ev.payload })),
  onBackupUpdate: localEvent('backup-update', (ev) => ({ serverId: ev.serverId, event: ev.event, uuid: ev.uuid, data: ev.data })),
  onScheduleUpdate: localEvent('schedule-update'),
  onScheduleDeleted: localEvent('schedule-deleted', (ev) => ({ id: ev.id })),
  onScheduleRan: localEvent('schedule-ran'),

  minimizeWindow: () => ipcRenderer.invoke('win:minimize'),
  closeWindow: () => ipcRenderer.invoke('win:close'),
  quitApp: () => ipcRenderer.invoke('win:quit'),
})
